version: '3.8'

services:
  tests:
    image: buildkite/plugin-tester:latest
    volumes:
      - .:/plugin:ro
    working_dir: /plugin
    environment:
      - BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_ADVANCED_DEBUG_MODE=true
      - BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_ADVANCED_DRY_RUN=true
    command: bats tests/

  lint:
    image: buildkite/plugin-linter:latest
    volumes:
      - .:/plugin:ro
    working_dir: /plugin
    command: plugin-linter

  python-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/lib
      - BUILDKITE_COMMAND_EXIT_STATUS=1
      - BUILDKITE_COMMAND=npm test
      - BUILDKITE_BUILD_PATH=/tmp/test-build
      - BUILDKITE_PIPELINE_SLUG=test-pipeline
      - BUILDKITE_BUILD_ID=test-build-123
      - BUILDKITE_JOB_ID=test-job-456
      - BUILDKITE_STEP_KEY=test-step
      - BUILDKITE_BRANCH=main
      - BUILDKITE_COMMIT=abc123def456
      - AI_ERROR_ANALYSIS_PLUGIN_DIR=/app
    command: python3 -m pytest tests/python/ -v

  health-check:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/lib
      - AI_ERROR_ANALYSIS_PLUGIN_DIR=/app
      - BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_ADVANCED_DRY_RUN=true
    command: python3 lib/health_check.py

  integration-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - BUILDKITE_COMMAND_EXIT_STATUS=1
      - BUILDKITE_COMMAND=echo "Test error message" && exit 1
      - BUILDKITE_BUILD_PATH=/app
      - BUILDKITE_PIPELINE_SLUG=integration-test
      - BUILDKITE_BUILD_ID=integration-123
      - BUILDKITE_JOB_ID=integration-456
      - BUILDKITE_STEP_KEY=integration-step
      - BUILDKITE_BRANCH=main
      - BUILDKITE_COMMIT=integration123
      - AI_ERROR_ANALYSIS_PLUGIN_DIR=/app
      - BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_ADVANCED_DRY_RUN=true
      - BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_ADVANCED_DEBUG_MODE=true
    command: ./hooks/post-command

networks:
  default:
    name: ai-error-analysis-test