version: '3.8'

services:
  buildkite-agent:
    build:
      context: .
      dockerfile: Dockerfile.orbstack
    container_name: buildkite-agent-ai-analysis
    
    environment:
      # REQUIRED: Your Buildkite agent token
      BUILDKITE_AGENT_TOKEN: ${BUILDKITE_AGENT_TOKEN}
      
      # Agent configuration
      BUILDKITE_AGENT_NAME: ${BUILDKITE_AGENT_NAME:-orbstack-ai-agent}
      BUILDKITE_AGENT_TAGS: ${BUILDKITE_AGENT_TAGS:-queue=default,os=linux,orbstack=true,ai-error-analysis=enabled}
      
      # GitHub access (for HTTPS cloning)
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      BUILDKITE_GIT_CLONE_FLAGS: "-c http.extraheader='Authorization: Bearer ${GITHUB_TOKEN:-}'"
      
      # AI Provider Configuration (set at least one)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      
      # Plugin Configuration (from .env file)
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_PROVIDER: ${BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_PROVIDER}
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_MODEL: ${BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_MODEL}
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_MAX_TOKENS: ${BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_MAX_TOKENS}
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_ENABLE_CACHING: ${BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_ENABLE_CACHING}
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_DEBUG: ${BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_DEBUG}
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_SECRET_SOURCE_TYPE: ${BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_SECRET_SOURCE_TYPE}
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_API_KEY_ENV: ${BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_API_KEY_ENV}
      
      # Security settings
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_SECURITY_RUN_AS_NON_ROOT: "true"
      
    volumes:
      # Mount plugin source for development (optional - remove in production)
      - .:/buildkite/plugins/ai-error-analysis:ro
      
      # Persist build data
      - buildkite-builds:/buildkite/builds
      
      # Share Docker socket for Docker-in-Docker builds (optional)
      # - /var/run/docker.sock:/var/run/docker.sock
    
    networks:
      - buildkite-network
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Restart policy
    restart: unless-stopped
    
    # Security options
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    read_only: false  # Agent needs write access for builds
    user: "1000:1000"  # Run as non-root user
    
  # Optional: Run multiple agents
  buildkite-agent-2:
    extends: buildkite-agent
    container_name: buildkite-agent-ai-analysis-2
    environment:
      BUILDKITE_AGENT_NAME: ${BUILDKITE_AGENT_NAME:-orbstack-ai-agent-2}
    profiles:
      - scale

  buildkite-agent-3:
    extends: buildkite-agent
    container_name: buildkite-agent-ai-analysis-3
    environment:
      BUILDKITE_AGENT_NAME: ${BUILDKITE_AGENT_NAME:-orbstack-ai-agent-3}
    profiles:
      - scale

volumes:
  buildkite-builds:
    driver: local

networks:
  buildkite-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16