name: AI Error Analysis
description: Automatically analyzes build failures using AI models to provide actionable insights and suggestions
author: https://github.com/your-org/ai-error-analysis-buildkite-plugin
requirements:
  - python3
  - curl
  - jq

configuration:
  properties:
    # AI Provider Configuration
    ai_providers:
      type: array
      description: List of AI providers to use for error analysis
      default:
        - name: openai
          model: gpt-4o-mini
      items:
        type: object
        properties:
          name:
            type: string
            enum: ["openai", "claude", "gemini"]
            description: AI provider name
          model:
            type: string
            description: Model name (e.g., gpt-4.1, o4-mini, claude-opus-4, claude-sonnet-4, gemini-2.5-pro, gemini-2.5-flash)
          secret_source:
            type: object
            description: External secret management configuration
            properties:
              type:
                type: string
                enum: ["aws_secrets_manager", "vault", "gcp_secret_manager", "env_var"]
                default: "env_var"
              name:
                type: string
                description: Secret name or environment variable name
              region:
                type: string
                description: AWS region (for AWS Secrets Manager)
              vault_path:
                type: string
                description: Vault secret path
            additionalProperties: false
          endpoint:
            type: string
            description: Custom API endpoint (optional)
          max_tokens:
            type: integer
            description: Maximum tokens for response
            default: 1000
            minimum: 100
            maximum: 4000
          timeout:
            type: integer
            description: Request timeout in seconds
            default: 60
            minimum: 10
            maximum: 300
          use_batch_api:
            type: boolean
            description: Use batch API for 50% cost savings (non-real-time)
            default: false
        required: ["name"]
        additionalProperties: false

    # Error Detection Configuration  
    trigger:
      type: string
      enum: ["auto", "explicit", "always"]
      description: When to trigger error analysis
      default: "auto"

    conditions:
      type: object
      description: Conditions for triggering analysis
      properties:
        exit_status:
          type: array
          description: Exit codes that trigger analysis
          items:
            type: integer
            minimum: 1
            maximum: 255
          default: [1, 2, 125, 126, 127, 128, 130]
        branches:
          type: array
          description: Git branches to analyze (empty = all branches)
          items:
            type: string
            pattern: "^[a-zA-Z0-9._/-]+$"
          default: []
        patterns:
          type: array
          description: Log patterns that trigger analysis
          items:
            type: string
          default: ["ERROR", "FAILED", "Exception", "fatal:", "panic:"]
      additionalProperties: false

    # Context and Analysis Configuration
    context:
      type: object
      description: Context gathering configuration
      properties:
        log_lines:
          type: integer
          description: Number of log lines to analyze
          default: 500
          minimum: 50
          maximum: 2000
        include_environment:
          type: boolean
          description: Include safe environment variables in context
          default: true
        include_pipeline_info:
          type: boolean
          description: Include pipeline and build metadata
          default: true
        include_git_info:
          type: boolean
          description: Include git commit and branch information
          default: true
        custom_context:
          type: string
          description: Custom context to include in analysis
          default: ""
          maxLength: 2000
      additionalProperties: false

    # Security and Privacy
    redaction:
      type: object
      description: Log redaction configuration
      properties:
        custom_patterns:
          type: array
          description: Custom regex patterns to redact
          items:
            type: string
          default: []
        redact_file_paths:
          type: boolean
          description: Redact file paths that might contain user info
          default: true
        redact_urls:
          type: boolean
          description: Redact URLs that might contain sensitive data
          default: true
        enable_builtin_patterns:
          type: boolean
          description: Enable built-in secret detection patterns
          default: true
      additionalProperties: false

    # Output Configuration
    output:
      type: object
      description: Output configuration
      properties:
        annotation_style:
          type: string
          enum: ["error", "warning", "info", "success"]
          description: Buildkite annotation style
          default: "error"
        annotation_context:
          type: string
          description: Unique context for the annotation
          default: "ai-error-analysis"
          pattern: "^[a-zA-Z0-9_-]+$"
        include_confidence:
          type: boolean
          description: Include confidence score in output
          default: true
        save_as_artifact:
          type: boolean
          description: Save detailed analysis as build artifact
          default: false
        artifact_path:
          type: string
          description: Path for analysis artifact
          default: "ai-analysis-report.json"
          pattern: "^[a-zA-Z0-9._/-]+\\.json$"
      additionalProperties: false

    # Performance and Reliability
    performance:
      type: object
      description: Performance configuration
      properties:
        timeout:
          type: integer
          description: Total analysis timeout in seconds
          default: 120
          minimum: 30
          maximum: 600
        async_execution:
          type: boolean
          description: Run analysis asynchronously (don't block build)
          default: false
        cache_enabled:
          type: boolean
          description: Enable caching of similar error patterns
          default: true
        cache_ttl:
          type: integer
          description: Cache time-to-live in seconds
          default: 3600
          minimum: 300
          maximum: 86400
        fallback_strategy:
          type: string
          enum: ["round_robin", "priority", "fail_fast"]
          description: Strategy when primary AI provider fails
          default: "priority"
        retry_config:
          type: object
          description: Retry configuration with exponential backoff
          properties:
            max_attempts:
              type: integer
              default: 3
              minimum: 1
              maximum: 5
            initial_delay:
              type: integer
              description: Initial delay in seconds
              default: 2
              minimum: 1
              maximum: 10
            max_delay:
              type: integer
              description: Maximum delay in seconds
              default: 60
              minimum: 5
              maximum: 300
          additionalProperties: false
      additionalProperties: false

    # Advanced Configuration
    advanced:
      type: object
      description: Advanced configuration options
      properties:
        debug_mode:
          type: boolean
          description: Enable debug logging
          default: false
        dry_run:
          type: boolean
          description: Test configuration without calling AI APIs
          default: false
        input_validation:
          type: object
          description: Input validation configuration
          properties:
            enabled:
              type: boolean
              default: true
            max_log_size_mb:
              type: integer
              default: 50
              minimum: 1
              maximum: 200
            allowed_commands:
              type: array
              description: Whitelist of allowed commands for analysis
              items:
                type: string
              default: []
          additionalProperties: false
        custom_prompts:
          type: object
          description: Custom AI prompts for different error types
          properties:
            default:
              type: string
              description: Default analysis prompt
              maxLength: 2000
            compilation_error:
              type: string
              description: Prompt for compilation errors
              maxLength: 2000
            test_failure:
              type: string
              description: Prompt for test failures
              maxLength: 2000
            deployment_error:
              type: string
              description: Prompt for deployment errors
              maxLength: 2000
            security_error:
              type: string
              description: Prompt for security-related errors
              maxLength: 2000
          additionalProperties: false
        security:
          type: object
          description: Security configuration
          properties:
            enable_command_validation:
              type: boolean
              description: Validate commands against injection attacks
              default: true
            container_security:
              type: object
              description: Container security settings
              properties:
                run_as_non_root:
                  type: boolean
                  default: true
                drop_capabilities:
                  type: array
                  items:
                    type: string
                  default: ["ALL"]
                add_capabilities:
                  type: array
                  items:
                    type: string
                  default: []
                no_new_privileges:
                  type: boolean
                  default: true
              additionalProperties: false
          additionalProperties: false
        rate_limit:
          type: object
          description: Rate limiting configuration
          properties:
            requests_per_minute:
              type: integer
              default: 30
              minimum: 1
              maximum: 100
            burst_limit:
              type: integer
              default: 10
              minimum: 1
              maximum: 50
          additionalProperties: false
      additionalProperties: false

  additionalProperties: false