name: AI Error Analysis
description: Analyzes build failures using AI to provide insights and solutions
author: https://github.com/your-org/ai-error-analysis-buildkite-plugin
requirements:
  - python3
  - curl
  - jq

configuration:
  properties:
    provider:
      type: string
      enum: ["openai", "anthropic", "gemini"]
      description: "AI provider to use for analysis"
    
    model:
      type: string
      description: "Specific AI model to use (optional, provider default used if not specified)"
    
    api_key_env:
      type: string
      description: "Environment variable containing the API key (fallback for external secrets)"
      default: "{PROVIDER}_API_KEY"
    
    max_tokens:
      type: integer
      minimum: 100
      maximum: 4000
      default: 1000
      description: "Maximum tokens for AI response"
    
    temperature:
      type: number
      minimum: 0.0
      maximum: 2.0
      default: 0.1
      description: "AI model temperature for response randomness"
    
    enable_caching:
      type: boolean
      default: true
      description: "Enable prompt caching for cost savings"
    
    cache_ttl:
      type: integer
      minimum: 300
      maximum: 86400
      default: 3600
      description: "Cache time-to-live in seconds"
    
    # External Secret Management (2025 Security Standard)
    secret_source:
      type: object
      description: "External secret management configuration (required for production)"
      properties:
        type:
          type: string
          enum: ["aws_secrets_manager", "vault", "gcp_secret_manager", "env_var"]
          description: "Type of secret management system"
        
        # AWS Secrets Manager
        secret_name:
          type: string
          description: "AWS Secrets Manager secret name"
        region:
          type: string
          default: "us-east-1"
          description: "AWS region for Secrets Manager"
        
        # HashiCorp Vault
        vault_path:
          type: string
          description: "Vault secret path (e.g., secret/buildkite/api-key)"
        vault_role:
          type: string
          description: "Vault AppRole for authentication"
        vault_addr:
          type: string
          description: "Vault server address (uses VAULT_ADDR env var if not specified)"
        
        # Google Cloud Secret Manager
        project_id:
          type: string
          description: "GCP project ID for Secret Manager"
      additionalProperties: false
    
    # Multi-provider configuration (advanced)
    providers:
      type: array
      description: "Multiple AI providers with fallback (alternative to single provider)"
      items:
        type: object
        properties:
          provider:
            type: string
            enum: ["openai", "anthropic", "gemini"]
          model:
            type: string
          priority:
            type: integer
            minimum: 1
            maximum: 10
            default: 1
          secret_source:
            $ref: "#/configuration/properties/secret_source"
        required: ["provider"]
        additionalProperties: false
    
    fallback_strategy:
      type: string
      enum: ["priority", "round_robin", "fail_fast"]
      default: "priority"
      description: "Strategy when primary provider fails"
    
    # Context Configuration
    context:
      type: object
      description: "Build context configuration"
      properties:
        include_env_vars:
          type: boolean
          default: false
          description: "Include environment variables (security risk)"
        include_git_info:
          type: boolean
          default: true
          description: "Include git branch, commit, and author info"
        max_log_lines:
          type: integer
          minimum: 50
          maximum: 2000
          default: 500
          description: "Maximum log lines to analyze"
        custom_context:
          type: string
          maxLength: 1000
          description: "Custom context to include in analysis"
      additionalProperties: false
    
    # Output Configuration
    output:
      type: object
      description: "Output and reporting configuration"
      properties:
        style:
          type: string
          enum: ["error", "warning", "info", "success"]
          default: "error"
          description: "Buildkite annotation style"
        include_confidence:
          type: boolean
          default: true
          description: "Include AI confidence score in output"
        save_artifact:
          type: boolean
          default: false
          description: "Save detailed analysis as build artifact"
        artifact_path:
          type: string
          default: "ai-analysis.json"
          description: "Path for analysis artifact"
      additionalProperties: false
    
    # Performance Configuration
    performance:
      type: object
      description: "Performance and reliability settings"
      properties:
        timeout_seconds:
          type: integer
          minimum: 30
          maximum: 600
          default: 120
          description: "Analysis timeout in seconds"
        retry_attempts:
          type: integer
          minimum: 1
          maximum: 5
          default: 3
          description: "Number of retry attempts on failure"
        rate_limit_rpm:
          type: integer
          minimum: 1
          maximum: 100
          default: 30
          description: "Rate limit requests per minute"
        async_execution:
          type: boolean
          default: false
          description: "Run analysis asynchronously (don't block build)"
      additionalProperties: false
    
    # Security Configuration (2025 Standards)
    security:
      type: object
      description: "Security settings"
      properties:
        sanitize_logs:
          type: boolean
          default: true
          description: "Enable log sanitization before AI analysis"
        redact_secrets:
          type: boolean
          default: true
          description: "Automatically redact secrets from logs"
        allowed_domains:
          type: array
          items:
            type: string
          default: ["api.openai.com", "api.anthropic.com", "generativelanguage.googleapis.com"]
          description: "Allowed domains for API calls"
        run_as_non_root:
          type: boolean
          default: true
          description: "Enforce non-root container execution"
        enable_thinking_mode:
          type: boolean
          default: false
          description: "Enable extended thinking mode for supported models (Claude Opus 4)"
        enable_deep_think:
          type: boolean
          default: false
          description: "Enable Deep Think mode for supported models (Gemini Pro)"
      additionalProperties: false
    
    # Debug and Development
    debug:
      type: boolean
      default: false
      description: "Enable debug logging"
    
    dry_run:
      type: boolean
      default: false
      description: "Test configuration without calling AI APIs"

  # Either provider OR providers must be specified, but not both
  oneOf:
    - required: ["provider"]
      not:
        required: ["providers"]
    - required: ["providers"]
      not:
        required: ["provider"]

  additionalProperties: false