version: '3.8'

services:
  buildkite-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: buildkite-ai-error-test
    environment:
      # Buildkite Configuration
      BUILDKITE_AGENT_TOKEN: ${BUILDKITE_AGENT_TOKEN:-xxx-your-agent-token-here-xxx}
      BUILDKITE_AGENT_NAME: ${BUILDKITE_AGENT_NAME:-docker-test-agent}
      BUILDKITE_AGENT_TAGS: ${BUILDKITE_AGENT_TAGS:-docker=true,ai-error-analysis=true}
      
      # AI Provider Configuration (set one of these)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      
      # Plugin Configuration
      AI_PROVIDER: ${AI_PROVIDER:-openai}
      AI_MODEL: ${AI_MODEL:-gpt-4o}
      
      # Optional: Plugin debug mode
      BUILDKITE_PLUGIN_AI_ERROR_ANALYSIS_DEBUG: ${DEBUG:-false}
      
    volumes:
      # Mount the plugin source for development
      - ..:/home/buildkite/ai-error-analysis-buildkite-plugin:ro
      
      # Persist agent data
      - buildkite-builds:/home/buildkite/.buildkite-agent/builds
      
    networks:
      - buildkite
    
    # Uncomment to run the agent automatically
    # command: agent
    
    # Keep container running for testing
    stdin_open: true
    tty: true

  # Optional: Local test environment without agent
  test-env:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: buildkite-ai-error-test-env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
    volumes:
      - ..:/home/buildkite/ai-error-analysis-buildkite-plugin:ro
    networks:
      - buildkite
    command: bash
    stdin_open: true
    tty: true
    profiles:
      - test

volumes:
  buildkite-builds:

networks:
  buildkite:
    driver: bridge